### ISSUE TITLE
wg plugin: Clicking the disable checkbox triggers TypeError

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#144] opened 2023-05-12 16:59 UTC
Clicking the checkbox to disable wireguard in the VPN UI view triggers the below exception:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'put')
    at value (Wireguard.js:28:17)
    at n.value (Wireguard.js:58:53)
    at onValueChange (index.tsx:89:26)
    at onChange (index.js:52:7)
    at Object.He (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Or (react-dom.production.min.js:100:68)
    at Er (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
```

https://github.com/spr-networks/super/assets/1476421/0a513a8f-8c3e-4507-b042-e151205abf3e

**Comment by lts-po** [comment] 2023-05-16 11:43
Fixed in dev branch (https://github.com/spr-networks/super/commit/04256a2d26f2b29da76b2c036d64ce50f4c5ba77)

Will be avail in next release

**Comment by 0vercl0k** [comment] 2023-06-01 14:39
I just tried the opposite of this on `0.2.9` - trying to turn it on generate the below:

<img width="1128" alt="image" src="https://github.com/spr-networks/super/assets/1476421/d16e83e5-7a59-448d-ac63-8d608e306c10">

Let me know if I'm missing anything!

Cheers

**Comment by lts-po** [comment] 2023-07-27 14:49
Cannot reproduce, this one should be fixed in latest release

**Closed** 2023-10-11 12:13 UTC
