### ISSUE TITLE
[dns] Consider setting coredns forward max_concurrent N by default

### ISSUE THREAD

**Issue by cocochpie** [spr-networks/super#161] opened 2023-06-04 18:35 UTC
I don't know if this is due to my broadband environment,
At some point, my internet was a little slow, so I SSH to it and saw that the htop and
Coredns was excessively using 300% of all CPU resources all the time.

I didn't see anything special in the docker logs. So i did a quick google search and found the same issue.

So I added "max_concurrent 1000" to the forward configuration and ran "docker-compose restart dns" and it calmed down.

- https://github.com/coredns/coredns/issues/4544
- https://github.com/kubernetes-sigs/kubespray/pull/9307

Please consider adding max_concurrent 1000 or N to the default configuration.

**Comment by lts-po** [comment] 2023-06-05 15:23
Will add this to default config & include in next release. Thanks @cocochpie

**Comment by lts-rad** [comment] 2023-06-07 00:09
This just reproduced for me. I am wondering if it's not a regression with coredns as this behavior is new.

**Comment by lts-rad** [comment] 2023-06-07 00:13
@lts-po i am suspecting this is actually related to jsonlog instead

**Comment by lts-rad** [comment] 2023-06-07 00:49
https://github.com/coredns/coredns/pull/5951 this is the last big commit i think that likely changed the way timeouts work.

i will see if a reverted coredns reproduces.

oddly enough the cpu spiek triggers off for me immediately, with barely any dns requests going through

**Comment by cocochpie** [comment] 2023-06-07 01:17
Yeah, I saw a comment in a issue ticket somewhere that dangling connections seem to explode the moment cloudflare dns fails to connect. it's weird.

**Comment by cocochpie** [comment] 2023-06-07 01:20
@lts-rad And I guess I'm wrong, it was fine yesterday, but now Coredns is crazy again, even with the max_connection setting.

**Comment by lts-rad** [comment] 2023-06-07 01:27
@cocochpie yeah i think they took on a risky commit in master, i am evaluating now with the last release v1.10.1

**Comment by lts-rad** [comment] 2023-06-07 01:33
disabling jsonlog and block i think the problem goes away. @lts-po i am investigating now but i suspect it is sprbus related

**Comment by lts-rad** [comment] 2023-06-07 01:44
Temporary workaround (but disables ad blocking):

```
#  block enable_superapi
```

while i investigate

**Comment by lts-rad** [comment] 2023-06-07 07:48
i've tracked this down to issues with the CGO=0 sqlite dependency that was in use. it looks like they underwent some code changes and introduced some bugs.  the code is easy enough to replace though and can be simplified. we will kick off a new build soon to bring everything up to date

https://github.com/spr-networks/coredns-block/pull/1

**Comment by cocochpie** [comment] 2023-06-08 06:00
@lts-rad Got it. my coredns is going crazy again today even i used "# block enable_superapi".
Now i just ran docker-compose pull && up -d . Let's see

**Comment by 0vercl0k** [comment] 2023-06-08 17:13
I updated yesterday to 0.2.11 and just caught this this morning:

<img width="797" alt="image" src="https://github.com/spr-networks/super/assets/1476421/823061f0-c7bc-4b5b-a83f-279303a3efac">

**Comment by lts-rad** [comment] 2023-06-08 18:11
took awhile for me to trigger. i am investigating now

```
root@pib:~# go tool pprof http://localhost:6053
Fetching profile over HTTP from http://localhost:6053/debug/pprof/profile

Saved profile in /root/pprof/pprof.coredns.samples.cpu.002.pb.gz
File: coredns
Type: cpu
Time: Jun 8, 2023 at 6:10pm (UTC)
Duration: 30.14s, Total samples = 31.25s (103.68%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 23.34s, 74.69% of 31.25s total
Dropped 95 nodes (cum <= 0.16s)
Showing top 10 nodes out of 60
      flat  flat%   sum%        cum   cum%
     7.32s 23.42% 23.42%      7.78s 24.90%  runtime.(*itabTableType).find
     3.06s  9.79% 33.22%      5.05s 16.16%  runtime.mallocgc
     2.70s  8.64% 41.86%     10.48s 33.54%  runtime.getitab
     1.89s  6.05% 47.90%      1.89s  6.05%  sync.(*Mutex).Unlock
     1.62s  5.18% 53.09%      7.35s 23.52%  crypto/tls.(*Conn).Read
     1.53s  4.90% 57.98%      1.53s  4.90%  sync.(*Mutex).Lock (inline)
     1.46s  4.67% 62.66%      8.81s 28.19%  io.ReadAtLeast
     1.27s  4.06% 66.72%     25.70s 82.24%  github.com/miekg/dns.(*Conn).ReadMsgHeader
     1.26s  4.03% 70.75%      1.72s  5.50%  crypto/tls.(*Conn).handshakeContext
     1.23s  3.94% 74.69%      6.47s 20.70%  runtime.assertI2I2
(pprof) 
```

**Comment by lts-rad** [comment] 2023-06-08 18:22
Thanks @0vercl0k . i am currently doing back testing against previous versions. 


RUN git clone --depth 1 --branch v1.10.0 https://github.com/coredns/coredns.git


i wonder how long the issue takes to trigger, or if there is a good reproduction.

when running dns queries in a loop from multiple clients i can of course get coredns to spike but it settles back down. so i am trying to find a reliable reproducer that leaves coredns in a bad state.

**Comment by lts-rad** [comment] 2023-06-08 18:32
Seems like the issue takes hours to reproduce. I have this running for now, will check back later and se ehow it did.

https://github.com/spr-networks/super/pull/168

**Comment by lts-rad** [comment] 2023-06-09 13:34
@cocochpie does the latest .12 build work for you? on this end it has not reproduced when pinning to v1.10.0

**Comment by cocochpie** [comment] 2023-06-10 02:49
@lts-rad Sadly, it's still the same for me. I don't know why. It takes me hours to get to 300% CPU too.

**Comment by cocochpie** [comment] 2023-06-10 03:00
Ok, I have CoreDNS-1.10.0 image now. I'll be back.

**Comment by lts-rad** [comment] 2023-06-10 05:46
@cocochpie interesting it reproduced for you. can you add pprof to your configuration and check top15? 
https://coredns.io/plugins/pprof/

on this end v .12 has been good

**Comment by cocochpie** [comment] 2023-06-10 06:15
@lts-rad Thank you. Maybe i did some mistake updating before, it's been 3 hours and the CPU usage is fine. 
I'll look at the CPU usage more and turn on pprof later.

**Comment by cocochpie** [comment] 2023-06-10 12:42
@lts-rad It's been 6 hours and everything is good! thank you
and just for the case, I have pprof turned on now. I'll see how it goes tomorrow and if everything is fine, I'll turn it back off.

**Comment by lts-rad** [comment] 2023-06-10 22:28
Great. Still a mystery why this issue is triggering. I filed with upstream here https://github.com/coredns/coredns/issues/6151

**Comment by cocochpie** [comment] 2023-06-11 06:15
It's very stable now, thank you so much

**Comment by lts-rad** [comment] 2023-06-12 05:40
@cocochpie glad to here, thats what i am seeing on this end too. i still need to find a reproducer that triggers it on latest coredns, I want to understand what the bug is

**Comment by lts-rad** [comment] 2023-06-28 01:16
I'm going to close this issue as fixed for us but this is now technical debt for getting onto mainline coredns

**Closed by lts-rad** 2023-06-28 01:16 UTC
